# Generated by Django 3.2.9 on 2021-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisitiontime',
            fields=[
                ('timeid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('starttime', models.CharField(blank=True, max_length=25, null=True)),
                ('endtime', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'acquisitiontime',
                'managed': False,
            },
        ),
    ]
